import './globals.css'
import { Metadata } from 'next'

function Header(){
  return(
    <header className='text-red-500'>
      Header
    </header>
  )
}

function Footer(){
  return(
    <footer className='text-red-500'>
      Footer
    </footer>
  )

}


export const metadata: Metadata = {
  title: {
    default: 'mytitle',
    template: '%s | MyApp',
    // absolute: 'xyz'
  },
  description: 'Generated by Next.js',
}

export default function NewLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-black'>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
